"""
Parse all HIL log files and extract the most common byte value per position per CAN ID.
Outputs a PowerShell $knownValues hashtable snippet for generate_dbc_html.ps1.

Log format (per line, ignoring # comments):
  timestamp_ms  can_id_decimal  dlc  b0  b1  b2 ... (hex bytes)
"""

import os
import sys
from collections import defaultdict, Counter

LOG_DIR = r"E:\HIL_LOGS"
MIN_OCCURRENCES = 5  # skip IDs seen fewer than this many times

# Accumulate: {can_id: {byte_pos: Counter}}
byte_counters = defaultdict(lambda: defaultdict(Counter))
id_count = Counter()

for fname in os.listdir(LOG_DIR):
    if fname.endswith('.err.log'):
        continue
    fpath = os.path.join(LOG_DIR, fname)
    try:
        with open(fpath, 'r', errors='replace') as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith('#'):
                    continue
                parts = line.split()
                if len(parts) < 3:
                    continue
                try:
                    can_id = int(parts[1])
                    dlc = int(parts[2])
                    bytes_data = [int(b, 16) for b in parts[3:3+dlc]]
                except (ValueError, IndexError):
                    continue
                if len(bytes_data) != dlc:
                    continue
                id_count[can_id] += 1
                for pos, val in enumerate(bytes_data):
                    byte_counters[can_id][pos][val] += 1
    except Exception as e:
        print(f"# Warning: {fname}: {e}", file=sys.stderr)

# Build output
print("# Auto-generated by extract_known_values.py from HIL logs")
print("# Most common byte value per position per CAN ID")
print("# Only IDs with >= {} occurrences included".format(MIN_OCCURRENCES))
print("$knownValues = @{")

for can_id in sorted(byte_counters.keys()):
    if id_count[can_id] < MIN_OCCURRENCES:
        continue
    byte_dict = byte_counters[can_id]
    max_pos = max(byte_dict.keys())
    vals = []
    for pos in range(max_pos + 1):
        if pos in byte_dict:
            most_common = byte_dict[pos].most_common(1)[0][0]
            vals.append('0x{:02X}'.format(most_common))
        else:
            vals.append('0x00')
    hex_id = '0x{:03X}'.format(can_id)
    print("    {} = @({})  # {} occurrences, {} bytes".format(
        can_id, ', '.join(vals), id_count[can_id], max_pos + 1))

print("}")
